version: '3.8'

services:
  web:
    build: .
    # image: ghcr.io/betterandbetterii/the-reader:latest
    expose:
      - "8000"  # 只暴露给内部网络，不对外暴露
    volumes:
      - ./persist:/app/persist
    environment:
      - DEBUG=1
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:1.16.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx:ro
      - ./nginx/logs:/var/log/nginx
    restart: always
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 
    