# Generated by Django 5.1.4 on 2024-12-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_textsection_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsection',
            name='text',
        ),
        migrations.AddField(
            model_name='textsection',
            name='section',
            field=models.JSONField(default=dict, help_text='Section对象'),
        ),
    ]
