# Generated by Django 5.1.4 on 2025-01-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_textsection_text_textsection_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='sections',
        ),
        migrations.AddField(
            model_name='document',
            name='chinese_sections',
            field=models.ManyToManyField(blank=True, related_name='chinese_documents', to='api.textsection'),
        ),
        migrations.AddField(
            model_name='document',
            name='english_sections',
            field=models.ManyToManyField(blank=True, related_name='english_documents', to='api.textsection'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='集合名称', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
                ('documents', models.ManyToManyField(related_name='collections', to='api.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
                ('collections', models.ManyToManyField(related_name='projects', to='api.collection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
