# Generated by Django 5.1.4 on 2025-01-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_document_sections_document_chinese_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='collection_id',
            field=models.IntegerField(default=0, help_text='集合ID'),
        ),
    ]
