# Generated by Django 5.1.4 on 2025-01-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_task_collection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
