# Generated by Django 5.1.6 on 2025-02-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_mindmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="api_type",
            field=models.CharField(
                default="gemini", help_text="API 类型 (gemini 或 openai)", max_length=10
            ),
        ),
    ]
